"""Add punches_achieved column to punchcards

Revision ID: 9e5aef16e4f8
Revises: b912d84a0bc3
Create Date: 2025-01-26 15:59:44.553125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5aef16e4f8'
down_revision: Union[str, None] = 'b912d84a0bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
