"""Add business model and punches_achieved

Revision ID: b912d84a0bc3
Revises: 57b07825b2b8
Create Date: 2025-01-26 15:54:20.375763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b912d84a0bc3'
down_revision: Union[str, None] = '57b07825b2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('punchcards', sa.Column('punches_achieved', sa.Integer(), nullable=True))
    op.alter_column('punchcards', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('visits_pos_transaction_id_key', 'visits', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('visits_pos_transaction_id_key', 'visits', ['pos_transaction_id'])
    op.alter_column('punchcards', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('punchcards', 'punches_achieved')
    op.alter_column('businesses', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
